### ISSUE TITLE
Updating to include our Sphinx extensions

### ISSUE THREAD

**Issue by timgdavies** [OpenDataServices/sphinx-base#1]
I suspect we should add:

* https://github.com/OpenDataServices/sphinxcontrib-jsonschema 
* https://github.com/OpenDataServices/sphinxcontrib-opendataservices 

to requirements.txt and have a quick demo of these in this base. 

That would help make sure we have a version tested for compatible dependencies of these (which has given me a few issues in the past)

**Comment by Bjwebb** [comment]
Yes, I think this makes sense.

**Comment by Bjwebb** [comment]
I've done this:
https://sphinx-base.readthedocs.io/en/latest/
https://github.com/OpenDataServices/sphinx-base

Note that due to a weird ongoing pip/setuptools issue, you'll need three extra requirements related files, and to modify the "Requirements file" listed on readthedocs https://github.com/OpenDataServices/sphinx-base/commit/bc01824affe8eac3d3edf8ad6486a948f895fccd#diff-04c6e90faac2675aa89e2176d2eec7d8R58
